Feat/temps passe service
gip-inclusion/dora pull request #115
Opened 2024-12-06 07:57 UTC by jbuget

:information_source: PR re-créée à partir de #23 

### 🍣 Problème

En tant que Éditeur d’un Service pour ma Structure, je souhaite indiquer, pour le-dit service, le temps passé (en nombre d'heures par semaine et en nombre de semaines) par le Bénéficiaire afin d’aider à l’orientation d’un service par les Accompagnateurs tout en satisfaisant aux obligations légales à venir (loi Travail 2025).

### 🦄 Solution

Ajouter 1 section ("Durée de la prestation") avec 2 champs dans le formulaire d'édition d'une structure :

- 1 champ numérique pour indiquer le volume horaire hebdomadaire
- 1 champ numérique pour préciser le nombre de semaines

### ✅ Pour tester

Il faut se connecter à un compte Gestionnaire de structure et modifier un Service. La section devrait être visible avec les 2 champs éditable.

### 🍀 Misc

Côté implémentation front-end, on utilise, modifie et enrichit le composant `<BasicInputField/>` pour qu'il supporte correctement le type "number".

Jusqu'à présent, on l'utilisait avec des types ["text", "tel", "email"] tous basés sur une valeur de type String. Il a fallu l'adapter pour supporter aussi le type `Number`. Conséquence : nécessite quelques `.toString()` à certains endroits.

Sur le modèle du type "tel", il a fallu définir des handlers spécifiques pour s'assurer que le format Number reste valide.

Côté utilisateur, on empêche l'utilisateur de saisir autre chose que des chiffres. On fait en sorte qu'il puisse quand même effacer la valeur et enregistrer (sans erreur) le formulaire.

### 👓 Revue de code

On peut y aller commit-par-commit 🧘‍♂️.

2024-12-11 09:52 UTC, jbuget commented
![](https://github.trello.services/images/mini-trello-icon.png) [Editer le nombre d'heure d'un service](https://trello.com/c/CU1hbd75/166-editer-le-nombre-dheure-dun-service)

2024-12-11 09:53 UTC, jbuget commented
![](https://github.trello.services/images/mini-trello-icon.png) [Lire le nombre d'heure d'un service](https://trello.com/c/rcHZGknP/167-lire-le-nombre-dheure-dun-service)

2024-12-11 15:23 UTC, ggounot requested changes
Beau travail ! Cela fonctionne bien. Juste quelques remarques sur le code.

Ça me frustre toujours un peu quand un composant de saisie de nombre renvoie du texte, et qu'on doive gérer les cas `undefined`, `null` et `""` comme valides dans une fonction isInteger(). Mais je sais aussi qu'il est toujours compliqué de gérer les entrées de nombres. J'imagine que le système que tu as implémenté est le meilleur que tu aies trouvé. On pourra en discuter à l'occasion.

2024-12-11 15:23 UTC, ggounot commented on front/src/lib/components/specialized/services/fields-duration.svelte
> +  <div class="hint-total-duration">
Autant utiliser Tailwind CSS :)

```suggestion
  <div class="font-bold">
```

Et tu peux supprimer le CSS.

2024-12-11 15:23 UTC, ggounot commented on front/src/lib/validation/schema-utils.ts
> +  if (value === undefined || isNaN(value)) {
```suggestion
  if (isNaN(value)) {
```

`isNaN(undefined) === true`

2024-12-12 08:13 UTC, jbuget commented on back/dora/data_inclusion/mappings.py
> +        "duration_weeks": None,
Non, pas à ma connaissance. Je confirme auprès de l'équipe.

2024-12-12 08:16 UTC, jbuget commented on back/dora/services/models.py
> +        verbose_name="Durée",
Je confirme. J'ai mis le nom du libellé du champ côté IHM / maquette. Après, c'est une information back-end, on doit pouvoir le nommer comme il nous arrange, côté tech.

2024-12-12 08:40 UTC, jbuget commented on back/dora/services/serializers.py
> +            "duration_weeks",
ok, je comprends et je retire. merci.

2024-12-12 08:42 UTC, jbuget commented on back/dora/support/serializers.py
> +            "duration_weeks",
ok, je retire.

2024-12-12 08:42 UTC, jbuget commented on back/dora/support/serializers.py
> +            "duration_weeks",
ok, je retire.

2024-12-12 08:44 UTC, jbuget commented on front/src/lib/components/forms/fields/basic-input-field.svelte
> +        <input type="text" bind:value inputmode="numeric" {...props} />
Non, car pour être consistant avec le reste de l'UX, on autorise à mettre des mauvaises valeurs en live et on affiche un message d'erreur à la soumission, plutôt que modifier l'input de l'user à la volée, de façon un pue sauvage et un peu bizarre (pour que ce soit ok, il faudrait qu'on ai ce type de mécanisme pour tous les champs et qu'on ait un feedback pour avertir l'usager qu'on modifie sa saisie pour telle et elle raison)

2024-12-12 08:46 UTC, jbuget commented on front/src/lib/components/specialized/services/fields-duration.svelte
> +  <div class="hint-total-duration">
Bien vu. Au départ il y avait plus de choses, mais à la fin il ne restait plus que le gras.

2024-12-12 08:52 UTC, jbuget commented on front/src/lib/validation/schema-utils.ts
> +  if (value === undefined || isNaN(value)) {
oh ! je ne savais pas. merci pour cet apprentissage.

2024-12-12 13:34 UTC, jbuget commented on back/dora/services/models.py
> +        verbose_name="Durée",
Confirmé. Ces 2 chamsp seront intégrés au schéma lors d'une prochaine version le mois prochain. Il me semble qu'on a déjà une US pour ça.

2024-12-12 14:20 UTC, ggounot commented on front/src/lib/components/forms/fields/basic-input-field.svelte
> +        <input type="text" bind:value inputmode="numeric" {...props} />
Je ne pensais pas à changer la saisie, mais à avoir le retour en erreur dès l'événement _blur_. C'est ce qui est fait pour les autres champs justement.

2024-12-12 14:29 UTC, jbuget commented on front/src/lib/components/forms/fields/basic-input-field.svelte
> +        <input type="text" bind:value inputmode="numeric" {...props} />
ok, après vérification, j'avais mal compris le comportement. je change.

2024-12-17 13:37 UTC, jbuget commented on front/src/lib/components/forms/fields/basic-input-field.svelte
> +        <input type="text" bind:value inputmode="numeric" {...props} />
ajout du `onBlur` ainsi que du `onChange`

2024-12-17 13:52 UTC, ggounot commented on front/src/lib/components/forms/fields/basic-input-field.svelte
> +        <input type="text" bind:value inputmode="numeric" {...props} />
Top, la vérification de l'entièreté du nombre ne se fait pas au blur, étonnamment. Mais elle est bien faite à la soumission du formulaire donc ce n'est pas grave.

2024-12-17 13:54 UTC, ggounot approved these changes

2024-12-17 14:08 UTC, ggounot approved these changes

2024-12-17 14:09 UTC, merged