feat(analytics) : Ajout d'une sous-application analytics
gip-inclusion/dora pull request #144
Opened 2024-12-19 14:25 UTC by vperron

Les commits sont découpés pour aider à la compréhension.

L'idée est de passer doucement d'un modèle avec des scripts SQL non managés dans dora-back, à:
- une application séparée, tournant dans son propre conteneur (`dora-analytics`, avec sa propre base PostgreSQL)
- un script de synchronisation simple et exhaustif : uniquement les tables nécessaires sont copiées de `dora-back-prod`
- une collection de scripts SQL managés par [DBT](https://www.getdbt.com/product/what-is-dbt), une référence
- une validation et linting poussés (paranoïaque ?) du SQL utilisé pour les transformations
- des vues et tables intermédiaires optimisées pour les analytics (jointures & index optimisés)
- un tout nouveau Metabase, à jour, sur inclusion.gouv.fr, ciblant `dora-analytics`, avec le SSO Google et des permissions strictes
- bonus, un outils d'analyse de Metabase, à partager éventuellement.

Les deux Metabase peuvent coexister en attendant, de même que les scripts de synchronisation actuels.

Les questions et dashboards les plus utiles seront à porter individuellement dans le nouveau Metabase en faisant attention aux [bonnes pratiques Metabase](https://www.notion.so/gip-inclusion/Bonnes-pratiques-Metabase-1595f321b6048043822ef4f44d1b89f0) , cc @laurinehu .

2025-01-08 18:22 UTC, laurinehu commented on analytics/models/staging/stg_structure.sql
> +        CONCAT('https://dora.inclusion.beta.gouv.fr/structures/', structures.slug) AS dora_url
et du coup 

```
dora_url("structures", structures.slug) as dora_url
```

2025-01-13 08:43 UTC, vperron commented on analytics/models/staging/stg_service.sql
> +        CONCAT('https://dora.inclusion.beta.gouv.fr/services/', services.slug) AS dora_url
alors attention parce que les macros il vaut mieux en faire un usage limité.
- elles ne sont pas analysées par SQLFluff qui ne peut pas les comprendre
- ça casse la "code locality" autrement dit maintenant tu dois aller voir dans le fichier de la macro pour comprendre ce que fait le code, que tu aurais compris tout de suite sinon
- les macros sont peu intuitives : elles peuvent etre des one-liner comme ici ou des choses très complexes

du coup, en tout cas à DI, on a opté pour minimiser absolument leur usage pour conserver une bonne maintenabilité; on ne les utilise que dans des cas où VRAIMENT ça permet de ne pas écrire par exemple, 100 fois le meme snippet l'un sous l'autre. Et encore quand ça arrive, on se dit que ce qu'on veut faire n'est pas top ^^

2025-01-27 15:45 UTC, jbuget commented on analytics/models/staging/stg_pageview.sql
> +        CAST(date AS DATE) >= '2024-07-01'
pourquoi cette date en dur ?

2025-01-27 15:50 UTC, jbuget commented on analytics/sync-analytics.sh
> +time pg_dump $DORA_DATABASE_URL --jobs=8 --format=directory --compress=1 --clean --if-exists --no-owner --no-privileges --verbose $(cat args.txt) --file=/tmp/out.dump
thought: j'ai un mauvais _a priori_ sur l'option `--if-exists` qui m'a le plus souvent desservi qu'autre chose et s'est avéré source de problèmes ou difficultés ou erreurs ou alertes.  

En l'occurrence, ici, je ne savais pas qu'on pouvait la mettre (avec `--clean`) dans un `pg_dump`. J'ai appris un truc.

Mais quand même, y en a vraiment besoin ?

2025-01-28 07:08 UTC, service-dev-gip-inclusion commented
![](https://github.trello.services/images/mini-trello-icon.png) [(Victor) Industrialiser la synchro SQL : mettre en place DBT](https://trello.com/c/j4tsMjTi/292-victor-industrialiser-la-synchro-sql-mettre-en-place-dbt)

2025-01-28 09:49 UTC, jbuget commented on analytics/models/staging/stg_service.sql
> +        END                              AS update_status
@vperron l'a repris tel quel depuis [la table `mb_all_service` historique](https://github.com/gip-inclusion/dora/blob/2b994895198bb9e3b461e7a8491fec06ec31fe16/back/queries/metabase/01-base/0020_mb_all_service.sql#L50-L62).

Ca permet de créer une étiquette utilisée dans les questions Metabase pour segmenter les services publiés, non-publiés et ceux nécessitant une actualisation (dont la date de dernière modification remonte à plus de 9 mois).

2025-01-28 17:58 UTC, jbuget requested changes
❌ Je pense qu'il faut redéplacer tels quels (en remettant les préfixes pour le sous-dossier "01-base") les scripts SQL initiaux afin de ne pas casser la synchro actuelle. 

Si on envoie la PR en prod en l'état : 
* la synchro ne se fera pas sur le nouveau Metabase car on doit gérer un nouveau sous-dossier du mono-repo (dans Scalingo)
* l'ancienne synchro ne se fera plus car le script `back/tools/update-db.sh` ne trouvera plus de scripts SQL à parcourir, rendant les données et dashboards existants obsolètes

2025-01-29 09:51 UTC, jbuget submitted a review, later dismissed
Merci @vperron pour tout le taff. 🚀 LGTM !

2025-01-29 14:00 UTC, jbuget approved these changes

2025-01-29 14:00 UTC, merged