Pro connect migration
gip-inclusion/dora pull request #19
Opened 2024-10-23 11:02 UTC by ikarius

# Backend migration ProConnect

Cette PR ajoute la couche technique OIDC nécessaire à une connexion à ProConnect (PC).
La couche de connexion Inclusion-Connect (IC) reste en place comme solution de repli en cas de problèmes lors du déploiement de PC.

## Utilisation de mozilla-django-oidc

La quasi-totalité du flow OIDC est géré par la librairie `mozilla-django-oidc` choisie pour sa simplicité et parce que déjà utilisée par d'autres startups de l'écosystème beta.gouv.
Son code est simple, lisible et peut-être facilement assimilé et étendu au besoin (ce qui est notre cas).

La mise en oeuvre de `mozilla-django-oidc` est essentiellement déclarative :
la plupart des actions, endpoints, callbacks .. sont configurables via de simple `settings Django.

Pour les aspects :
    - création et récupération d'utilisateur,
    - personnalisation des interactions : SAFIR, SIRET ...
    - déconnexion

certaines portions de la librairie ont dues être enrobées ou étendues pour ajouter ces fonctionnalités.

## Configuration de Django pour PC :

Voir tous les paramètres Django préfixés OIDC_ , ainsi que :

    - `LOGIN_REDIRECT_URL`
    - `LOGOUT_REDIRECT_URL` : pour les 2 étapes de déconnexion,
    - `OIDC_CALLBACK_CLASS` : pour le gestionnaire d'identification personnalisé.

## Description des particularités DORA / PC

### Connexion au frontend

Pour la connectique IC, certaines parties du flow OIDC sont implémentées coté frontend (appels initiaux, callbacks).

Pour PC, tout est centralisé au niveau du backend.

Une fois le flow OIDC terminé, un token DRF est transmis à la partie frontend pour être stocké sous forme d'entrée `localStorage` (même mécanisme que pour la connexion actuelle avec IC).

Ce mécanisme devra être revu, ou au moins renforcé une fois IC complètement décommissionné.

Ajouts d'étapes intermédiaires dans le flow OIDC

### `oidc/oidc_logged_in`

Après le callback d'identification OIDC pour permettre :
    - de gérer correctement la redirection en cas de `next_url` ,
    - de passer le token DRF au frontend.

### `oidc/oidc_pre_logout`

Une déconnexion complète avec PC nécessite 2 étapes, dans l'ordre :
 -  effacement des données PC sur le site PC via un token stocké à la connexion et un endpoint spécifique (effacement des cookies du domaines PC),
 -  l'effacement de la session sur le serveur Django.

Mal gérer cette phase mène à des états de connexion instables et dans certains cas des problèmes de redirections infinies.
Adaptation de certaines fonctions OIDC

Essentiellement représentées par des vues Django et le gestionnaire d'identification.
Vue CustomLogoutView

Enrobe la vue de déconnexion de mozilla-django-oidc pour permettre les deux étapes :

    vérification d'un state ,
    redirection vers le logout de PC,
    effacement de la session Django.

Vue CustomAuthorizationCallbackView

Permet essentiellement de bien gérer le paramètre next_url et d'effectuer correctement la redirection entre backend et frontend après une identification réussie.
Gestionnaire OIDCAuthenticationBackend

La création d'un gestionnaire d'identification personnalisé est nécessaire pour plusieurs raisons.

D'abord à cause d'un problème (?) d'implémentation par PC lors du retour du token JWT.
Le type de contenu de la réponse n'est pas celui attendu, et un reformatage du token est nécessaire pour éviter une erreur de traitement (voir get_user_info).

Ensuite les traditionnelles étapes de création ou de récupération d'un utilisateur existant après une identification réussie doivent être améliorés pour :

    la récupération du SIRET et éventuellement du code SAFIR,
    utiliser un token DRF plutôt que l'identication par défaut de Django,
    le stockage du sub OIDC en base (pour l'instant pas utilisé).

Voir les méthodes :

    get_user,
    update_user,
    create_user,
    get_user_info : pour le reformatage du token.

2024-10-23 14:00 UTC, ggounot requested changes
Sacré travail. C'est propre et très bien documenté. Chapeau !

Petit soucis cependant :

Après avoir fait une recherche, je me connecte avec Pro Connect.

Mon URL passée par par le paramètre next est : `/recherche?city=75112&cl=Paris (75)&l=Rue de Lyon 75012 Paris&lat=48.849221&lon=2.370927`

À la fin du processus d'identification, je suis redirigé vers : `/recherche?city=75112
`
Il y a donc perte de paramètres de l'URL.

En revanche, quand je me connecte à partir d'une page service avec seulement l'ID de la recherche dans l'URL : `/services/bimbamjob-jlgu-titre-professionnel-?searchId=194805` je suis bien redirigé vers cette exacte URL.

2024-10-23 15:07 UTC, ggounot commented
![](https://github.trello.services/images/mini-trello-icon.png) [PRO-CONNECT : préparer le socle technique](https://trello.com/c/tGX5MRjq/136-pro-connect-pr%C3%A9parer-le-socle-technique)

2024-10-24 14:25 UTC, ikarius commented on front/src/app.postcss
> +    background-image: url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnIHdpZHRoPScyMTEnIGhlaWdodD0nNTgnIGZpbGw9J25vbmUnPjxnIGNsaXAtcGF0aD0ndXJsKCNhKSc+PHBhdGggZmlsbD
Oui, c'était la recommandation de ProConnect, mais comment dire ...

C'est corrigé

2024-10-24 14:55 UTC, ikarius commented on back/dora/oidc/views.py
> +    redirect_uri = f"{settings.FRONTEND_URL}/auth/pc-callback/{token}/"
Donc ici, ce sera un _won't fix_ si proche de la MEP ProConnect. Mais comme précisé, j'aimerais virer ce token DRF et la manière actuelle de s'identifier vers le back (les A/R `auth/user-info`)

2024-10-24 16:25 UTC, ggounot commented on front/src/app.postcss
> +    background-image: url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnIHdpZHRoPScyMTEnIGhlaWdodD0nNTgnIGZpbGw9J25vbmUnPjxnIGNsaXAtcGF0aD0ndXJsKCNhKSc+PHBhdGggZmlsbD
Mieux comme ça ! Merci :)

2024-10-24 16:42 UTC, ggounot commented on front/.env-example
> +VITE_OIDC_AUTH_BACKEND=# proconnect | inclusionconnect
Peut-ètre mettre `proconnect` par défaut ?

2024-10-24 16:42 UTC, ggounot commented on front/src/app.postcss
> +  }
Pourquoi ne pas utiliser directement `sr-only` ?

2024-10-24 16:42 UTC, ggounot commented on front/src/lib/components/specialized/pc-button.svelte
> +      Besoin d’aide&nbsp;? Contactez-nous
Espace fine insécable

```suggestion
      Besoin d’aide&#8239;? Contactez-nous
```

2024-10-24 16:42 UTC, ggounot commented on front/src/lib/components/specialized/pc-button.svelte
> +      Qu'est que ProConnect&nbsp;?
Espace fine insécable

```suggestion
      Qu'est que ProConnect&#8239;?
```

2024-10-24 16:42 UTC, ggounot commented on front/src/lib/components/specialized/pc-button.svelte
> +      title="Qu’est-ce que ProConnect ? nouvelle fenêtre"
Espace fine insécable

```suggestion
      title="Qu’est-ce que ProConnect ? nouvelle fenêtre"
```

2024-10-24 16:42 UTC, ggounot commented on front/src/lib/components/specialized/pc-button.svelte
> +    getApiURL() + "/oidc/login/?next=" + encodeURIComponent(nextPage);
```suggestion
  $: loginUrl = `${getApiURL()}/oidc/login/?next=${encodeURIComponent(nextPage)}`;
```

2024-10-24 16:42 UTC, ggounot commented on front/src/routes/auth/connexion/+page.svelte
> +                <div>DORA passe à Inclusion Connect&nbsp!</div>
```suggestion
                <div>DORA passe à Inclusion Connect&#8239;!</div>
```

2024-10-24 16:42 UTC, ggounot commented on front/src/routes/auth/connexion/+page.svelte
> +            Pourquoi ProConnect&nbsp;?
```suggestion
            Pourquoi ProConnect&#8239;?
```

2024-10-24 16:42 UTC, ggounot commented on front/src/routes/auth/connexion/+page.svelte
> +              🧑🏻‍💻 Un compte unique pour tous vos services numériques !
```suggestion
              🧑🏻‍💻 Un compte unique pour tous vos services numériques&#8239;!
```

2024-10-24 16:42 UTC, ggounot commented on front/src/routes/auth/connexion/+page.svelte
> +              🧑🏻‍💻 Un compte unique pour tous vos services numériques !
```suggestion
              🧑🏻‍💻 Un compte unique pour tous vos services numériques&#8239;!
```

2024-10-24 17:01 UTC, ikarius commented on front/src/app.postcss
> +  }
cette classe n'est normalement plus utilisée, j'ai oublié de la supprimer. Merci !

2024-10-25 09:17 UTC, ikarius commented on front/src/lib/components/specialized/pc-button.svelte
> +      Besoin d’aide&nbsp;? Contactez-nous
_TIL_ espace fine insécable a.k.a `&#8239`

2024-10-25 09:29 UTC, ikarius commented on front/src/lib/components/specialized/pc-button.svelte
> +    getApiURL() + "/oidc/login/?next=" + encodeURIComponent(nextPage);
Je veux bien, mais pourquoi le rendre dynamique ? Rien ne bouge la dedans.

2024-10-25 12:22 UTC, ggounot commented on front/src/lib/components/specialized/pc-button.svelte
> +      Qu'est que ProConnect&nbsp;?
La règle veut qu'on utilise une espace _fine_ insécable avant les signes de ponctuation double (?!:;), dans les guillemets français («») et avant certains symboles (€%). L'espace insécable normale est utilisée dans les autres contextes où il faut une espace insécable.

2024-10-25 12:25 UTC, ggounot commented on front/src/lib/components/specialized/pc-button.svelte
> +    getApiURL() + "/oidc/login/?next=" + encodeURIComponent(nextPage);
Oui ça ne change rien en pratique. Mais quand il y a des dépendances, et qu'on ne sait pas toujours si elles peuvent changer ou pas, je me dis que toujours utiliser $: permet de ne pas se poser de questions. Ce n'est qu'une proposition non bloquante, tu peux laisser comme ça :)

2024-10-25 12:27 UTC, ggounot commented on front/src/routes/auth/connexion/+page.svelte
> +  console.log("AUTH", OIDC_AUTH_BACKEND);
```suggestion
```

2024-10-25 12:33 UTC, ikarius commented on front/src/routes/auth/connexion/+page.svelte
> +  console.log("AUTH", OIDC_AUTH_BACKEND);
Oubli degueu de ma part merci

2024-10-26 05:59 UTC, ikarius commented
Je viens de marquer les deux dernières correction de typos comme terminées.
Je passe la migration ProConnect en staging pour vérifications avant lundi.

2024-10-26 06:05 UTC, merged