feat: add script to import Cresus structures and services
gip-inclusion/dora pull request #57
Opened 2024-11-08 16:38 UTC by jbuget

### Problème

Le but de la tâche est d’intégrer dans DORA les données de structures, services et administrateurs depuis [un tableau Google Spreadsheet](https://docs.google.com/spreadsheets/d/1Ojgck9YWE3RBO6lQ9AKBbpQ3bwNzJB2KV2cTXhfVDmA/edit?gid=0#gid=0), fourni par @Lucas PASTEL.

### Solution

Vu le peu de données à importer (_seulement_ une vingtaine de structures et une centaine de services), l'équipe a pris la décision de se contenter d'un script python one-shot à effectuer directement en production (mais tout de même revu au préalable).

### Réalisation

https://www.notion.so/gip-inclusion/Import-des-donn-es-Cr-sus-1375f321b60480db8c88fd7755e0bf16?pvs=4

2024-11-08 16:39 UTC, jbuget commented
![](https://github.trello.services/images/mini-trello-icon.png) [Import CRESUS](https://trello.com/c/jm32vDFL/233-import-cresus)

2024-11-20 16:43 UTC, ggounot commented on back/scripts/import_cresus_services.py
> +from types import SimpleNamespace
Formater le fichier avec Ruff

2024-11-20 16:43 UTC, ggounot commented on back/scripts/import_cresus_structures.py
> +from types import SimpleNamespace
Formater le fichier avec Ruff

2024-11-20 16:48 UTC, ggounot commented on back/scripts/import_cresus_structures.py
> +                print(f"\tErreur inattendue - {e}", file=sys.stderr)
J'ai 2 erreurs inattendues :

> Traitement de la ligne 2 :
>         Création d'une nouvelle structure pour le SIRET 82242934600015
>         Établissement trouvé pour le SIRET 82242934600015. Création à partir de celui-ci.
>         Erreur inattendue - Users must have an email address
> 
> Traitement de la ligne 3 :
>         Création d'une nouvelle structure pour le SIRET 39130260100045
>         Établissement trouvé pour le SIRET 39130260100045. Création à partir de celui-ci.
>         Erreur inattendue - Users must have an email address

Les structures sont tout de même créées mais pas comptabilisées.

2024-11-25 09:08 UTC, jbuget commented on back/scripts/import_cresus_services.py
> +    service.save()
Avec Lucas et Chloé, il a été décidé de mettre directement le statut `PUBLISHED`.

2024-11-25 09:10 UTC, jbuget commented on back/scripts/import_cresus_services.py
> +    service.address2 = data.location_complement
Très bien vu : j'ai créé une méthode `dora.services.utils#upate_geom(service)`, extraite de la _management command_ `dora.services.fix_services_geom` (sauf l'assert initial, pour plus de flexbilité dans d'autres contextes) utilisée dans la commande et donc dans le script `import_cresus_services`

2024-11-26 15:12 UTC, ggounot requested changes
Superbe travail ! Je sais que ça a été compliqué mais on y gagne de belles nouvelles fonctions utilitaires :)

Encore quelques petites remarques, désolé :p

2024-11-26 15:12 UTC, ggounot commented on back/scripts/import_cresus_services.py
> +    service.status = ServiceStatus.PUBLISHED
Il manque `location_kind`, `diffusion_zone_type` et `diffusion_zone_city` :flushed:

2024-11-27 10:18 UTC, ggounot commented on back/scripts/import_cresus_structures.py
> +            send_invitation_email(member, "L’équipe DORA")
Ah oui, au temps pour moi

2024-11-27 23:08 UTC, jbuget commented on back/dora/core/utils.py
> +        logger.error("Aucun résultat trouvé")
Je propose, pour avancer, d'appeler la BAN même en mode dry-run et de donner les lignes avec resultat incertain en fin de rapport
cf. capture : 
<img width="1512" alt="Capture d’écran 2024-11-27 à 23 39 43" src="https://github.com/user-attachments/assets/2d437f9f-ff9a-4cc1-aa7e-3941b2ad32d9">


C'est très loin d'être optimal, mais ça m'a permis de résoudre 28 problèmes sur les 31. Il reste 4 localisation trop chelou (ex : aire de camping-car ?!)

2024-11-28 08:07 UTC, ikarius commented
Je n'arrive que tardivement sur le script. 
D'abord : beau travail. 

Ensuite, avant de plonger dedans, quelques questions générales :
- la non-idempotence me gène un peu :  la plupart des scripts concernant les structures ou les imports ont adoptés cette approche pour plus de sécurité sur les MAJ de données (avec succès),
- je ne comprends pas (encore) le fait d'avoir besoin de faire des accès BAN : les services sont rattachés à des structures, qui sont nécessairement géolocalisées par le biais de la base SIRENE (c'est un des ses rôles principaux). Qu'a t'on besoin de géolocaliser ?
-  la promotion des scripts : il y aura probablement à reprendre certains éléments pour les réutiliser. Je ne pas convaincu par le fait d'en faire des `management commands` (trop spécifiques),
- par contre, les fonctions spécifiques de modification de structures et de création / modification de modèles devraient remonter vers les modèles correspondants pour être réutilisable au niveau métier.

2024-11-28 11:35 UTC, jbuget commented
🙏 Merci pour ces remarques @ikarius !

>     * la non-idempotence me gène un peu :  la plupart des scripts concernant les structures ou les imports ont adoptés cette approche pour plus de sécurité sur les MAJ de données (avec succès),

L'import des structures est idempotent. Pas les services. Je suis d'accord que ce n'est pas terrible. 

>     * je ne comprends pas (encore) le fait d'avoir besoin de faire des accès BAN : les services sont rattachés à des structures, qui sont nécessairement géolocalisées par le biais de la base SIRENE (c'est un des ses rôles principaux). Qu'a t'on besoin de géolocaliser ?

De ce que j'ai compris, une structure propose des "permanences" (ex : [ici](https://www.cresus.org/cresus-lorraine/)). Si je ne me trompe pas, les 502 services correspondent à `permanences * modeles_de_services`, soit 14 * 5 pour Crésus Lorraine.

Les permanences sont dans des points d'accueil différents.

Question : est-ce que selon toi, c'est un mauvais usage ou un usage détourné des Services qu'il faut proscrire ?

>     * la promotion des scripts : il y aura probablement à reprendre certains éléments pour les réutiliser. Je ne pas convaincu par le fait d'en faire des `management commands` (trop spécifiques),

Ce que j'ai en tête en cible : 
* parvenir à extraire la puer logique dans une classe ou un service dédié (et testé !)
* ajouter un mécanisme (via des boutons d'import) dans Django Admin (pas si simple, mais pas si compliqué)

>     * par contre, les fonctions spécifiques de modification de structures et de création / modification de modèles devraient remonter vers les modèles correspondants pour être réutilisable au niveau métier.

C'est ce que je m'attendais à trouver au tout début du chantier. Mais j'ai vu qu'on passait (à date) par des utilitaires, comme `instaniate_model`. Je suis d'accord avec toi. 

Reste une difficulté ou choix à faire, au cas où on les conserve, par rapport à aux appels à la BAN. J'aurai des remords à injecter des classes concrêtes techniques (ex : module `requests`ou une classe `BANClient` dans la classe `Service`. Mais je pars loin, il faut en discuter.

2024-12-03 10:43 UTC, ggounot commented on back/dora/core/utils.py
> +        logger.error("Aucun résultat trouvé")
Super !! Merci beaucoup pour cet effort, @jbuget !

2024-12-03 10:43 UTC, ggounot approved these changes
LGTM :rocket:

Je te laisse tranquille maintenant :wink:

2024-12-05 10:07 UTC, ikarius commented on back/dora/core/tests/test_utils.py
> +class UtilsTestCase(TestCase):
_nit_ : pourquoi au format Django et pas `pytest` ?

2024-12-05 10:07 UTC, ikarius commented on back/dora/core/tests/test_utils.py
> +            utils.get_geo_data(address="24 Rue du Commandant Guilbaud")
_nit_ : gros travail de patching, bravo

2024-12-05 10:13 UTC, ikarius approved these changes
LGTM
Pas beaucoup plus à dire que la dernière fois :
- un partie des éléments d'import de structure pourrait être réutilisés dans le processus actuel pour le renforcer
- la partie services pourrait être promue sous forme de `management command` puisqu'on a pas grand chose d'automatisé de ce coté là (peut-être dans le cadre de l'import SMILE ?)

2024-12-09 08:52 UTC, jbuget commented on back/dora/core/tests/test_utils.py
> +class UtilsTestCase(TestCase):
Aucune idée. C'était déjà comme ça. Je me suis contenté d'expliciter l'import. Mais peut-être que j'ai raté ou mal compris un truc.

2024-12-09 09:03 UTC, merged